# Generated by Django 2.1.5 on 2019-01-24 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20190108_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
