# Generated by Django 2.1.5 on 2019-01-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='uploaded_file',
            field=models.FileField(upload_to='image/'),
        ),
    ]
