# Generated by Django 2.1.5 on 2019-01-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20190124_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='uploaded_file',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
