# Generated by Django 2.1.5 on 2019-01-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20190124_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='uploaded_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
