# Generated by Django 2.1.5 on 2019-01-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20190125_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='uploaded_file',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
